# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import pydantic


class Author(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        validate_by_alias=True,
        validate_by_name=True,
    )
    id: int
    class_: str = pydantic.Field(
        alias="class",
    )
