# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Optional


class Author(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        validate_by_alias=True,
        validate_by_name=True,
    )
    id: int
    name: str
    bio: Optional[str]
