# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import enum
import pydantic
from typing import Optional


class BookStatus(str, enum.Enum):
    AVAILABLE = "available"
    CHECKED_OUT = "checked_out"
    OVERDUE = "overdue"


class Book(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        validate_by_alias=True,
        validate_by_name=True,
    )
    id: int
    title: str
    status: Optional[BookStatus]
    payload: my_lib.models.BookPayload
    metadata: Optional[my_lib.models.JsonValue]
