# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic

import my_lib.models


class Book(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        validate_by_alias=True,
        validate_by_name=True,
    )
    id: int
    payload: my_lib.models.Payload
