# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: query.sql
from typing import AsyncIterator, Iterator, Optional

import my_lib.models
import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_BOOK = """-- name: create_book \\:one
INSERT INTO books (payload)
VALUES (:p1)
RETURNING id, payload
"""


GET_BOOK = """-- name: get_book \\:one
SELECT id, payload FROM books
WHERE id = :p1 LIMIT 1
"""


LIST_BOOKS = """-- name: list_books \\:many
SELECT id, payload FROM books
ORDER BY id
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_book(self, *, payload: my_lib.models.Payload) -> Optional[models.Book]:
        row = self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": payload}).first()
        if row is None:
            return None
        return models.Book(
            id=row[0],
            payload=row[1],
        )

    def get_book(self, *, id: int) -> Optional[models.Book]:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK), {"p1": id}).first()
        if row is None:
            return None
        return models.Book(
            id=row[0],
            payload=row[1],
        )

    def list_books(self) -> Iterator[models.Book]:
        result = self._conn.execute(sqlalchemy.text(LIST_BOOKS))
        for row in result:
            yield models.Book(
                id=row[0],
                payload=row[1],
            )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_book(self, *, payload: my_lib.models.Payload) -> Optional[models.Book]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": payload})).first()
        if row is None:
            return None
        return models.Book(
            id=row[0],
            payload=row[1],
        )

    async def get_book(self, *, id: int) -> Optional[models.Book]:
        row = (await self._conn.execute(sqlalchemy.text(GET_BOOK), {"p1": id})).first()
        if row is None:
            return None
        return models.Book(
            id=row[0],
            payload=row[1],
        )

    async def list_books(self) -> AsyncIterator[models.Book]:
        result = await self._conn.stream(sqlalchemy.text(LIST_BOOKS))
        async for row in result:
            yield models.Book(
                id=row[0],
                payload=row[1],
            )
